# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchurl,
  fetchFromGitHub,
}:
{
  algermusicplayer-arm = {
    pname = "algermusicplayer-arm";
    version = "4.9.0";
    src = fetchurl {
      url = "https://github.com/algerkong/AlgerMusicPlayer/releases/download/v4.9.0/AlgerMusicPlayer-4.9.0-linux-arm64.AppImage";
      sha256 = "sha256-Evuh6HQhubA4WrQlVot+BCD2avrqpJaxz/L3+AB7sRc=";
    };
  };
  algermusicplayer-x86 = {
    pname = "algermusicplayer-x86";
    version = "4.9.0";
    src = fetchurl {
      url = "https://github.com/algerkong/AlgerMusicPlayer/releases/download/v4.9.0/AlgerMusicPlayer-4.9.0-linux-x86_64.AppImage";
      sha256 = "sha256-fY8lobsRg2nDENYDY3R81zJ2x0Fr29vJccrelbdggmg=";
    };
  };
  danmakufactory = {
    pname = "danmakufactory";
    version = "v1.70";
    src = fetchFromGitHub {
      owner = "hihkm";
      repo = "DanmakuFactory";
      rev = "v1.70";
      fetchSubmodules = false;
      sha256 = "sha256-dPgWVJuNOzTc+ocMyGHBb4ExB9P1Wu+uTQ62UejAAfE=";
    };
  };
  danmakufactory-git = {
    pname = "danmakufactory-git";
    version = "847d3c377ab8521c71a4b92c50403865ec0994b9";
    src = fetchFromGitHub {
      owner = "hihkm";
      repo = "DanmakuFactory";
      rev = "847d3c377ab8521c71a4b92c50403865ec0994b9";
      fetchSubmodules = true;
      sha256 = "sha256-SeAX1YgKNZou0+RYnSu8Cnxcv2G/gvwMCO6HkxT5pfc=";
    };
    date = "2025-10-01";
  };
  lxgw-wenkai-gb = {
    pname = "lxgw-wenkai-gb";
    version = "v1.521";
    src = fetchTarball {
      url = "https://github.com/lxgw/LxgwWenkaiGB/releases/download/v1.521/lxgw-wenkai-gb-v1.521.tar.gz";
      sha256 = "sha256-sryAhrDy/nayJTxSmiI41ULp1rVyjIBArJaIT1DOp54=";
    };
  };
  mpv-handler = {
    pname = "mpv-handler";
    version = "v0.4.1";
    src = fetchFromGitHub {
      owner = "akiirui";
      repo = "mpv-handler";
      rev = "v0.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-uWV9pjZp5s8H1UDS/T0JK//eJNnsaaby88l/tDqlQHY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./mpv-handler-v0.4.1/Cargo.lock;
      outputHashes = {

      };
    };
  };
  pixes = {
    pname = "pixes";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "wgh136";
      repo = "pixes";
      rev = "v1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-J6ap9kuiRyjZQHW5z4LyM9ww2FCDmgv5+qML5/YldNA=";
    };
    "pubspec.lock" = builtins.readFile ./pixes-v1.2.0/pubspec.lock;
  };
  pixes-git = {
    pname = "pixes-git";
    version = "558832d188014bff1b388232f453c269b8fdfaf7";
    src = fetchFromGitHub {
      owner = "wgh136";
      repo = "pixes";
      rev = "558832d188014bff1b388232f453c269b8fdfaf7";
      fetchSubmodules = false;
      sha256 = "sha256-J6ap9kuiRyjZQHW5z4LyM9ww2FCDmgv5+qML5/YldNA=";
    };
    "pubspec.lock" =
      builtins.readFile ./pixes-git-558832d188014bff1b388232f453c269b8fdfaf7/pubspec.lock;
    date = "2025-08-10";
  };
  splayer-git = {
    pname = "splayer-git";
    version = "ecadf6ade70fc827a09d9d6d5af0c8dfd07c9e14";
    src = fetchFromGitHub {
      owner = "imsyy";
      repo = "SPlayer";
      rev = "ecadf6ade70fc827a09d9d6d5af0c8dfd07c9e14";
      fetchSubmodules = false;
      sha256 = "sha256-UfbEnpQbPy/L/meMPR2vF9ojyYBP5P84LfxoSB7h6GQ=";
    };
    date = "2025-10-13";
  };
  uosc-danmaku = {
    pname = "uosc-danmaku";
    version = "v2.0.0";
    src = fetchFromGitHub {
      owner = "Tony15246";
      repo = "uosc_danmaku";
      rev = "v2.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-r4HcrDh4iW8ErfClfX1gkEWp7lVKbLE88fpj3tjYBAI=";
    };
  };
  uosc-danmaku-git = {
    pname = "uosc-danmaku-git";
    version = "4d9e54e1ade827d3f0963d9609dbd7658466491a";
    src = fetchFromGitHub {
      owner = "Tony15246";
      repo = "uosc_danmaku";
      rev = "4d9e54e1ade827d3f0963d9609dbd7658466491a";
      fetchSubmodules = false;
      sha256 = "sha256-Pmsw2XeGZPhKiduUsw8QH/VtpvemB6EbuvLnzCjKfQw=";
    };
    date = "2025-10-12";
  };
  vulkan-hdr-layer-kwin6 = {
    pname = "vulkan-hdr-layer-kwin6";
    version = "303e0c69e1d33acd95158d92b1fc652fb5b85399";
    src = fetchFromGitHub {
      owner = "Zamundaaa";
      repo = "VK_hdr_layer";
      rev = "303e0c69e1d33acd95158d92b1fc652fb5b85399";
      fetchSubmodules = true;
      sha256 = "sha256-NsC44Ifl/fAHvFqP7NLrVZ71Y+x5mBEkv+r43HN5yn4=";
    };
    date = "2025-07-31";
  };
  zhuque = {
    pname = "zhuque";
    version = "v0.212";
    src = fetchurl {
      url = "https://github.com/TrionesType/zhuque/releases/download/v0.212/ZhuqueFangsong-v0.212.zip";
      sha256 = "sha256-u4tmGnZD0ilqctnRBTCgCUlBnE5Sf7YXg/c8K6GowGI=";
    };
  };
}
