image: nixos/unstable

packages:
  - nixos.cachix

environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
  repo: "nix-config"
  cachix: "misterio"
  nur: "misterio"

secrets:
  - f2907d38-97b4-4e7d-9fb9-57b3fb0135af

tasks:
- setup_cachix: |
    cachix authtoken --stdin < ~/.cachix_token
    cachix use "$cachix"
- build: |
    cd "$repo"
    schemes=$(nix eval --raw .#generated-gtk-themes --apply 's: builtins.concatStringsSep "," (builtins.attrNames s)')
    gtk_themes=$(eval echo .#generated-gtk-themes.{${schemes/override,overrideDerivation,}})

    nix build .#{clematis,comma,minicava,pass-wofi,photoprism,preferredplayer,rgbdaemon,shellcolord,swayfader}
    nix build $gtk_themes -o result-gtk-themes

- upload_cachix: |
    nix path-info "$repo"/result*/ -r | cachix push "$cachix"
- update_nur: |
    curl -XPOST "https://nur-update.herokuapp.com/update?repo=${nur}"
