apiVersion: v1
kind: Pod
metadata:
  name: httpd-teste
  labels:
    app.kubernetes.io/name: httpd-teste
    app: httpd-teste
spec:
  containers:
  - name: httpd-teste
    image: httpd
    ports:
      - containerPort: 80
        protocol: TCP
        name: http
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-teste-service
spec:
  selector:
    app: httpd-teste
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpd-teste-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: teste.whiterun.lucao.net
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: httpd-teste-service
              port:
                number: 80

