language: nix
script:
  - bash ci/deploy.sh

notifications:
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.net#nixos-nur"
    template:
      - "%{result} - %{branch} \"%{commit_subject}\" %{build_url}"
