language: nix
nix: 2.3.4

notifications:
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.net#nixos-nur"
    template:
      - "%{result} - %{branch} \"%{commit_subject}\" %{build_url}"

before_script:
  - echo "trusted-users = $USER" | sudo tee -a /etc/nix/nix.conf
  - sudo systemctl restart nix-daemon
jobs:
  include:
    - name: test pull request
      script: bash ci/test.sh
      if: type = pull_request

    - name: update nur / nur-combined
      script: bash ci/update-nur.sh
      if: branch = master AND type != pull_request

    - name: update nur-search/data/packages.json
      script: ci/update-nur-search.sh
      if: branch = master AND type != pull_request
