#! /usr/bin/env bash

# load time in chromium: 15 seconds for 4300 packages

show_package_names=true

set -eu

# generated by scripts/join-eval-results.sh
packages_json_path="$1"

echo '<!DOCTYPE html>'
echo '<html lang="en">'
echo '<head>'
echo '<meta charset="utf-8">'
echo '<title>NUR packages</title>'
cat <<'EOF'
<style>
a { text-decoration: none; }
a:hover { color: orange; }
td {
  overflow-wrap: break-word;
  word-break: break-all;
}
h1, h2, h3 { font-weight: normal; }
</style>
EOF
# no. requires class="colname" on every <td>
# https://github.com/javve/list.js
#echo '<script src="list.min.js"></script>'
#echo '<script src="list.js"></script>' # debug

# no
# https://github.com/grid-js/gridjs
#echo '<script src="gridjs.umd.js"></script>'
#echo '<link href="mermaid.min.css" rel="stylesheet" />'

cat <<'EOF'
<!-- https://www.jsdelivr.com/package/npm/tablefilter -->
<script src="tablefilter.min.js"></script>
<link href="tablefilter.min.css" rel="stylesheet">
EOF

cat <<'EOF'
<script>
  window.onload = () => {
    // https://github.com/koalyptus/TableFilter
    var tf = new TableFilter(document.querySelector('#packages'), {
      auto_filter: { delay: 1000 },
      state: {
        types: ['hash'],
      },
    });
    tf.init();
  };
</script>
</body>
</html>
EOF

echo '</head>'
echo '<body>'
echo '<h1>nur-packages</h1>'

echo '<table width="100%" id="packages">'

echo '<thead>'
echo '<tr>'
if $show_package_names; then
  echo '<td width="33%">name</td>'
  echo '<td width="33%">attribute</td>'
  echo '<td>description</td>'
else
  echo '<td width="50%">attribute</td>'
  echo '<td>description</td>'
fi
echo '</tr>'
echo '</thead>'

echo '<tbody class="list">'

<"$packages_json_path" jq -r '
  to_entries[] |
  "<tr>\n" + (
    if '$show_package_names'
    then "<td>" + (
      if .value.meta.homepage == null then ""
      else "<a href=\"" + .value.meta.homepage + "\">"
      end
    ) + .value.name + (
      if .value.meta.homepage == null then ""
      else "</a>"
      end
    ) + "</td>\n"
    else ""
    end
  ) + "<td>" + (
    if .value._nurUrl == null then (
      .key
    ) else (
      "<a href=\"" + .value._nurUrl + "\">" + .key + "</a>"
    ) end
  ) + "</td>\n<td>" + (
    if .value.meta.description == null then "" else
    .value.meta.description |
    gsub("&"; "&amp;") |
    gsub("<"; "&lt;") |
    gsub(">"; "&gt;") |
    gsub("\n"; "<br>") |
    .
    end
  ) + "</td>\n</tr>"
'

echo '</tbody>'

echo '</table>'
