#! /usr/bin/env bash

# load time in chromium: 15 seconds for 4300 packages

show_package_names=true

nur_combined_blob_url='https://github.com/milahu/NUR/blob/'
nur_combined_repos_url="$nur_combined_blob_url"'nur-combined/repos/'

set -eu

# generated by scripts/join-eval-results.sh
packages_json_path="$1"

echo '<!DOCTYPE html>'
echo '<html lang="en">'
echo '<head>'
echo '<meta charset="utf-8">'
echo '<title>NUR packages</title>'
cat <<'EOF'
<style>
a { text-decoration: none; }
a:hover { color: orange; }
td {
  overflow-wrap: break-word;
  word-break: break-all;
}
h1, h2, h3 { font-weight: normal; }
#filter-columns-button { display: inline-block; }
.clickable { cursor: pointer; color: blue; }
.clickable:hover { color: orange; }
</style>
EOF
# no. requires class="colname" on every <td>
# https://github.com/javve/list.js
#echo '<script src="list.min.js"></script>'
#echo '<script src="list.js"></script>' # debug

# no
# https://github.com/grid-js/gridjs
#echo '<script src="gridjs.umd.js"></script>'
#echo '<link href="mermaid.min.css" rel="stylesheet" />'

cat <<'EOF'
<script>
  function filterColumns() {
    console.log("filterColumns");
    var button = document.querySelector("#filter-columns-button");
    if (button) {
      button.innerHTML = "Loading filters...";
      button.onClick = null;
      button.classList = [];
    }
    var fileDir = (document.location.href.slice(0, document.location.href.length - document.location.hash.length)).split("/").slice(0, -1).join("/");
    console.log(`filterColumns fileDir ${fileDir}`);
    var onLoad = () => {
      // https://github.com/koalyptus/TableFilter
      var tf = new TableFilter(document.querySelector('#packages'), {
        auto_filter: { delay: 1000 },
        state: {
          types: ['hash'],
        },
      });
      // fix: TableFilter could not load: tablefilter/style/tablefilter.css
      tf.getStylesheetPath = () => fileDir + "/tablefilter.min.css";
      console.log("filterColumns: tf.init");
      tf.init();
      var button = document.querySelector("#filter-columns-button");
      if (button) {
        console.log("filterColumns: button.remove");
        button.remove();
      }
    };
    var script = document.createElement("script");
    script.src = fileDir + "/tablefilter.min.js";
    console.log("filterColumns: script");
    script.addEventListener("load", onLoad);
    script.addEventListener("error", () => {
      throw new Error(`failed to load ${script.src}`);
    });
    document.head.appendChild(script);
  }
  window.onload = () => {
    if (document.location.hash) filterColumns();
  };
</script>
EOF

cat <<EOF
<base href="$nur_combined_repos_url">
EOF

echo '</head>'
echo '<body>'
echo '<h1>nur-packages</h1>'

cat <<'EOF'
<script>
  if (!document.location.hash)
    document.write('<div id="filter-columns-button" class="clickable" onClick="filterColumns()">Filter columns</div>');
</script>
EOF

echo '<table width="100%" id="packages">'

echo '<thead>'
echo '<tr>'
if $show_package_names; then
  echo '<td width="33%">name</td>'
  echo '<td width="33%">attribute</td>'
  echo '<td>description</td>'
else
  echo '<td width="50%">attribute</td>'
  echo '<td>description</td>'
fi
echo '</tr>'
echo '</thead>'

echo '<tbody class="list">'

<"$packages_json_path" jq -r '
  to_entries[] |
  "<tr>\n" + (
    if '$show_package_names'
    then "<td n>" + (
      if .value.meta.homepage == null then ""
      else "<a href=\"" + .value.meta.homepage + "\">"
      end
    ) + .value.name + (
      if .value.meta.homepage == null then ""
      else "</a>"
      end
    ) + "</td>\n"
    else ""
    end
  ) + "<td a>" + (
    if .value._nurUrl == null then (
      .key
    ) else (
      "<a href=\"" + .value._nurUrl + "\">" + .key + "</a>"
    ) end
  ) + "</td>\n<td d>" + (
    if .value.meta.description == null then "" else
    .value.meta.description |
    gsub("&"; "&amp;") |
    gsub("<"; "&lt;") |
    gsub(">"; "&gt;") |
    gsub("\n"; "<br>") |
    .
    end
  ) + "</td>\n</tr>"
'

echo '</tbody>'

echo '</table>'
