- name: Check if the closure path is already copied
  stat:
    path: "{{ nix_build_result }}"
  register: nix_build_result_stat

- name: Copy closure
  delegate_to: 127.0.0.1
  ansible.builtin.command: "nix-copy-closure --to {{ ssh_ip }} {{ nix_build_result }}"
  when: not nix_build_result_stat.stat.exists
