image: nixos/nix:latest

variables:
  NIX_PATH: "nixpkgs=channel:nixpkgs-unstable"

build:
  before_script:
    - nix-env -iA nixpkgs.cachix nixpkgs.bash nixpkgs.curl
    - cachix use alwinb
  script:
    - nix-build ci.nix -A buildOutputs
    - nix eval -f default.nix lib
    - nix eval -f default.nix modules
    - nix eval -f default.nix overlays
    - |
      if [ "$CI_COMMIT_REF_NAME" = "master" ] ; then
          echo "Push to Cachix and update NUR"
          nix-build ci.nix -A cacheOutputs | cachix push alwinb
          curl -sfSL -XPOST https://nur-update.herokuapp.com/update?repo=alwinb || true
      else
          echo "Do Nothing"
      fi
