# Helix text-editor interprets this file as documented here:
# - <https://github.com/helix-editor/helix/blob/master/book/src/languages.md>
#
# hack in support for nix-shell documents
# these have a shebang of `#!/usr/bin/env nix-shell`
# and a subsequent line: `#!nix-shell -i <lang> [args]`
[[language]]
name = "nix-shell"
scope = "source.nix_shell"
shebangs = [ "nix-shell" ]
file-types = [ "nix-shell" ]
injection-regex = "nix-shell"
indent = { tab-width = 2, unit = " " }
roots = []
grammar = "nix-shell"

[[grammar]]
name = "nix-shell"
source = { path = "@tree_sitter_nix_shell@" }
# source = { path = "/home/colin/dev/tree-sitter-nix-shell" }
# source = { git = "https://git.uninsane.org/colin/tree-sitter-nix-shell", rev = "c2fcc8b6ee91af2cb58a38f62c0800f82d783738" }

