[tool.poetry]
name = "pleroma-ebooks"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.8.3"
aiosqlite = "^0.17.0"
anyio = "^3.6.2"
beautifulsoup4 = "^4.11.1"
json5 = "^0.9.10"
markovify = "^0.9.4"
pendulum = "^2.1.2"

[tool.poetry.dev-dependencies]
setuptools = "^65.6.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
