# C
[candy]
src.git = "https://github.com/lanthora/candy"
fetch.github = "lanthora/candy"

#[koboldcpp]
#src.git = "https://github.com/LostRuins/koboldcpp"
#fetch.github = "LostRuins/koboldcpp"
#git.fetchSubmodules = true

[suyu]
src.git = "https://git.suyu.dev/suyu/suyu"
fetch.git = "https://git.suyu.dev/suyu/suyu"
git.fetchSubmodules = true

[nbfc-linux]
src.git = "https://github.com/nbfc-linux/nbfc-linux"
fetch.github = "nbfc-linux/nbfc-linux"

[llamafile]
src.git = "https://github.com/Mozilla-Ocho/llamafile"
fetch.github = "Mozilla-Ocho/llamafile"

[hyprwayland-scanner]
src.git = "https://github.com/hyprwm/hyprwayland-scanner"
fetch.github = "hyprwm/hyprwayland-scanner"
git.fetchSubmodules = true

# Dotnet

# Go
[open-snell]
src.git = "https://github.com/icpz/open-snell"
fetch.github = "icpz/open-snell"

[swgp-go]
src.git = "https://github.com/database64128/swgp-go"
src.branch = "main"
fetch.github = "database64128/swgp-go"

[mieru]
src.git = "https://github.com/enfein/mieru"
fetch.github = "enfein/mieru"

# Nodejs


# Python
[idntag]
src.git = "https://github.com/d99kris/idntag"
fetch.github = "d99kris/idntag"

[pynat]
src.git = "https://github.com/aarant/pynat"
fetch.github = "aarant/pynat"

[pystun3]
src.git = "https://github.com/talkiq/pystun3"
fetch.github = "talkiq/pystun3"

[bypy]
src.git = "https://github.com/houtianze/bypy"
fetch.github = "houtianze/bypy"

# Rust
[Anime4K-rs]
src.git = "https://github.com/andraantariksa/Anime4K-rs"
fetch.github = "andraantariksa/Anime4K-rs"

[av1an]
src.git = "https://github.com/master-of-zen/av1an"
fetch.github = "master-of-zen/av1an"

[ncmdump_rs]
src.git = "https://github.com/iqiziqi/ncmdump.rs"
fetch.github = "iqiziqi/ncmdump.rs"

[onedrive-fuse]
src.git = "https://github.com/oxalica/onedrive-fuse"
fetch.github = "oxalica/onedrive-fuse"

[rescrobbled]
src.git = "https://github.com/InputUsername/rescrobbled"
fetch.github = "InputUsername/rescrobbled"

[sakaya]
src.git = "https://github.com/donovanglover/sakaya"
fetch.github = "donovanglover/sakaya"

[waylyrics]
src.git = "https://github.com/waylyrics/waylyrics"
fetch.github = "waylyrics/waylyrics"

[aichat]
src.git = "https://github.com/sigoden/aichat"
fetch.github = "sigoden/aichat"

[fww-checkin-rs]
src.git = "https://github.com/1235467/fww-checkin-rs"
fetch.github = "1235467/fww-checkin-rs"

# Shell
[reflac]
src.git = "https://github.com/chungy/reflac"
fetch.github = "chungy/reflac"



# Overrides
[qcm]
src.git = "https://github.com/hypengw/Qcm"
fetch.github = "hypengw/Qcm"
git.fetchSubmodules = true

[sway]
src.git = "https://github.com/swaywm/sway"
fetch.github = "swaywm/sway"
git.fetchSubmodules = true

[hyprland]
src.git = "https://github.com/hyprwm/Hyprland"
fetch.github = "hyprwm/Hyprland"
git.fetchSubmodules = true

# Overrides deps
[wlroots]
src.git = "https://gitlab.freedesktop.org/wlroots/wlroots"
fetch.git = "https://gitlab.freedesktop.org/wlroots/wlroots"
git.fetchSubmodules = true

[wayland]
src.git = "https://gitlab.freedesktop.org/wayland/wayland"
fetch.git = "https://gitlab.freedesktop.org/wayland/wayland"
git.fetchSubmodules = true

[wayland-protocols]
src.git = "https://gitlab.freedesktop.org/wayland/wayland-protocols"
fetch.git = "https://gitlab.freedesktop.org/wayland/wayland-protocols"
git.fetchSubmodules = true

[libdrm]
src.git = "https://gitlab.freedesktop.org/mesa/drm"
fetch.git = "https://gitlab.freedesktop.org/mesa/drm"
git.fetchSubmodules = true

