# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  # fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "diffz-0.0.1-G2tlIQrOAQCfH15jdyaLyrMgV8eGPouFhkCeYFTmJaLk";
    path = fetchgit {
      url = "https://github.com/ziglibs/diffz.git";
      rev = "a20dd1f11b10819a6f570f98b42e1c91e3704357";
      hash = "sha256-y7Ck5XZNnHxmPPWlDAqZZ2g3n67txj5/Zq04AhuW5+M=";
    };
  }
  {
    name = "known_folders-0.0.0-Fy-PJtLDAADGDOwYwMkVydMSTp_aN-nfjCZw6qPQ2ECL";
    path = fetchgit {
      url = "https://github.com/ziglibs/known-folders";
      rev = "aa24df42183ad415d10bc0a33e6238c437fc0f59";
      hash = "sha256-YiJ2lfG1xsGFMO6flk/BMhCqJ3kB3MnOX5fnfDEcmMY=";
    };
  }
  {
    name = "lsp_codegen-0.1.0-CMjjo0ZXCQB-rAhPYrlfzzpU0u0u2MeGvUucZ-_g32eg";
    path = fetchgit {
      url = "https://github.com/zigtools/zig-lsp-codegen";
      rev = "063a98c13a2293d8654086140813bdd1de6501bc";
      hash = "sha256-KzRi/a3FCS11Mryin9skkf3rFrIuoMP8+RcU0IuYNBA=";
    };
  }
  {
    name = "lsp_kit-0.1.0-hAAxO8G9AACr9SwC5FsYac37Bn7yi968x2UMq4wxKlgr";
    path = fetchgit {
      url = "https://github.com/kristoff-it/zig-lsp-kit";
      rev = "46e2b958c02dc4ed2d4784f8841ba7d2076da783";
      hash = "sha256-yfBuIUiwJbFBev1nys3hmDIzaVfeSUJre7clqQvbavw=";
    };
  }
  {
    name = "zig_yaml-0.1.0-C1161hVrAgDsyB2EZnq-Vp-QuZ9xJm2y0dECRXGG3UaP";
    path = fetchgit {
      url = "https://github.com/kubkon/zig-yaml";
      rev = "27f63d3d2d13ed228d8fc077635205e6c2a405c7";
      # FIXME: Edited hash to the correct one, investigate...
      hash = "sha256-sDQHQ7uKDqAyvnEvfPheubn8C5QVWIXT9BdtT78UKeE=";
    };
  }
]
