# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bartender-6 = {
    pname = "bartender-6";
    version = "6-0-0";
    src = fetchurl {
      url = "https://macbartender.com/B2/updates/6-0-0/Bartender%206.dmg";
      name = "Bartender6.dmg";
      sha256 = "sha256-oJOGgkYRWNNOEMZ8iv+naPTVZxIf3oMb/K4WfvVwsnc=";
    };
  };
  flake-compat = {
    pname = "flake-compat";
    version = "flake-compat";
    src = fetchTarball {
      url = "https://git.lix.systems/lix-project/flake-compat/archive/main.tar.gz";
      sha256 = "sha256-NKw96t+BgHIYzHUjkTK95FqYRVKB8DHpVhefWSz/kTw=";
    };
    extract = {
      "default.nix" = ./. + "/sha256-NKw96t+BgHIYzHUjkTK95FqYRVKB8DHpVhefWSz_kTw=/default.nix";
    };
  };
  ghostty = {
    pname = "ghostty";
    version = "1.2.3";
    src = fetchurl {
      url = "https://release.files.ghostty.org/1.2.3/Ghostty.dmg";
      sha256 = "sha256-817pHxFuKAJ6ufje9FCYx1dbRLQH/4g6Lc0phcSDIGs=";
    };
  };
  ghostty-nightly = {
    pname = "ghostty-nightly";
    version = "tip";
    src = fetchurl {
      url = "https://github.com/ghostty-org/ghostty/releases/download/tip/ghostty-macos-universal.zip";
      sha256 = "sha256-rzuE082LklzW7Tz1eDTRDyms/hiViySuX7ucoPIDOo8=";
    };
  };
  helium-linux = {
    pname = "helium-linux";
    version = "0.7.9.1";
    src = fetchFromGitHub {
      owner = "imputnet";
      repo = "helium-linux";
      rev = "0.7.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-7bwEawrQWwtQXfg4u1dkJXoex1HE8chwn2FMtPkaidQ=";
    };
  };
  helium-macos = {
    pname = "helium-macos";
    version = "0.7.9.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-macos/releases/download/0.7.9.1/helium_0.7.9.1_arm64-macos.dmg";
      sha256 = "sha256-swFxWgHONhdzfLpwGVoje/ceTwCZFmoO3FBeIbjqIaY=";
    };
  };
  kanata = {
    pname = "kanata";
    version = "v1.10.1";
    src = fetchFromGitHub {
      owner = "jtroo";
      repo = "kanata";
      rev = "v1.10.1";
      fetchSubmodules = false;
      sha256 = "sha256-jzTK/ZK9UrXTP/Ow662ENBv3cim6klA8+DQv4DLVSNU=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-jzTK_ZK9UrXTP_Ow662ENBv3cim6klA8+DQv4DLVSNU=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  kanata-tray = {
    pname = "kanata-tray";
    version = "v0.8.0";
    src = fetchFromGitHub {
      owner = "rszyma";
      repo = "kanata-tray";
      rev = "v0.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-RTLFDB/irtEhEHwarROGmS4jNdRhruU1JKen48ADzZg=";
    };
  };
  kanata-vk-agent = {
    pname = "kanata-vk-agent";
    version = "8ce982af6a308788070c076619554d05375b6521";
    src = fetchFromGitHub {
      owner = "auscyber";
      repo = "kanata-vk-agent";
      rev = "8ce982af6a308788070c076619554d05375b6521";
      fetchSubmodules = false;
      sha256 = "sha256-hLRJcyaBNTl0dSPuoE7owwFqCcSrwqYo9yaF1O4wxk0=";
    };
    date = "2025-11-03";
  };
  karabiner-dk = {
    pname = "karabiner-dk";
    version = "v6.7.0";
    src = fetchFromGitHub {
      owner = "pqrs-org";
      repo = "Karabiner-DriverKit-VirtualHIDDevice";
      rev = "v6.7.0";
      fetchSubmodules = false;
      sha256 = "sha256-Yy1h8icYuJUZwU5vB01CAcqraEqugVSrp4dmhOrh58I=";
    };
  };
  musly = {
    pname = "musly";
    version = "v1.0.2";
    src = fetchFromGitHub {
      owner = "dddevid";
      repo = "musly";
      rev = "v1.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-TA8LLOeu2OeObAHEoRswuz38dWlLGFbfAAHmvO4TrYo=";
    };
  };
  yabai = {
    pname = "yabai";
    version = "v7.1.16";
    src = fetchFromGitHub {
      owner = "koekeishiya";
      repo = "yabai";
      rev = "v7.1.16";
      fetchSubmodules = false;
      sha256 = "sha256-WXvM0ub4kJ3rKXynTxmr2Mx+LzJOgmm02CcEx2nsy/A=";
    };
  };
  zen = {
    pname = "zen";
    version = "1.17.15b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.17.15b/zen.macos-universal.dmg";
      sha256 = "sha256-Lv7K5782E2ci5rtRA3SQpkZ+kVdOgYhD2Lc+L+gyFtA=";
    };
  };
  zen-twilight = {
    pname = "zen-twilight";
    version = "1.17.15b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/twilight/zen.macos-universal.dmg";
      sha256 = "sha256-DrtQ4ReiHWgL00x1Y9UDg9tVJC6yzH49lkxxbT+h+jM=";
    };
  };
}
