apiVersion: v1
kind: Pod
metadata:
  name: httpd-teste
  labels:
    app.kubernetes.io/name: httpd-teste
    app: httpd-teste
spec:
  containers:
  - name: httpd-teste
    image: traefik
    args:
      - traefik
      - --accesslog=true
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - containerPort: 80
        protocol: TCP
        name: http
      - containerPort: 8080
        protocol: TCP
        name: httpadm
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-teste-service
spec:
  selector:
    app: httpd-teste
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: httpadm
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpd-teste-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: traefik.whiterun.lucao.net
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: httpd-teste-service
              port:
                number: 80
  - host: traefik-admin.whiterun.lucao.net
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: httpd-teste-service
              port:
                number: 8080

