name: "macOS"
on:
  push:
jobs:
  build:
    strategy:
      matrix:
        platform: ["macos-latest"]
        channel: ["nixpkgs-unstable"]
    runs-on: "${{ matrix.platform }}"
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: "nixpkgs=channel:${{ matrix.channel }}"
      - uses: cachix/cachix-action@v7
        with:
          name: "aasg-nixexprs"
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: "nix-build --no-out-link --keep-going --show-trace ./ci.nix"
