image: nixos/nix:latest

variables:
  NIX_PATH: "nixpkgs=https://nixos.org/channels/nixos-18.09/nixexprs.tar.xz"

Build NUR:
  stage: build
  before_script:
    - nix-env -f https://cachix.org/api/v1/install -iA cachix
    - cachix use jomik
    - nix-env -f '<nixpkgs>' -iA curl
  script:
    - nix-build ci.nix -A buildOutputs
    - nix eval -f default.nix home-modules
    - >-
      [ "$CI_COMMIT_REF_NAME" = "master" ]
      && nix-build ci.nix -A cacheOutputs | cachix push jomik
      || echo "Not master"
    - >-
      [ "$CI_COMMIT_REF_NAME" = "master" ]
      && curl -sfSL -XPOST https://nur-update.herokuapp.com/update?repo=jomik
      || echo "Not master"
  except:
    - schedules
