---
kind: pipeline
name: default

steps:
- name: build
  image: nixos/nix
  commands:
  - nix-build ci.nix -A buildOutputs
  - nix eval -f default.nix 'lib'
  - nix eval -f default.nix 'modules'
  - nix eval -f default.nix 'overlays'
