---
- hosts: all
  become: false
  tasks:
    - name: Initializing
      import_tasks: tasks/load-vars.yaml

    - import_tasks: tasks/nix-build.yaml
      vars:
        nix_build_ref: ".#homeConfigurations.main.activationPackage"
      when: ansible_facts['os_family'] == "NixOS"

    - import_tasks: tasks/ssh-hostport.yaml

    - name: Show build result
      ansible.builtin.debug:
        msg: "System build path: {{ nix_build_result }}"

    - import_tasks: tasks/nix-copy-closure-to.yaml
      when: ansible_facts['os_family'] == "NixOS"

    - name: Apply home-manager generation right now
      ansible.builtin.shell: "HOME_MANAGER_BACKUP_EXT=backup {{ nix_build_result }}/bin/home-manager-generation -b backup"
      when: ansible_facts['os_family'] == "NixOS"

