---
- hosts: all
  become: false
  tasks:
    - name: Initializing
      import_tasks: tasks/load-vars.yaml

    - import_tasks: tasks/nix-build.yaml
      vars:
        nix_build_ref: "{{ playbook_dir }}/..#nixosConfigurations.{{ ansible_facts['hostname'] }}.config.system.build.toplevel"
      when: ansible_facts['os_family'] == "NixOS"

    - import_tasks: tasks/ssh-hostport.yaml

    - name: Show build result
      ansible.builtin.debug:
        msg: "System build path: {{ nix_build_result }}"

    - import_tasks: tasks/nix-copy-closure-to.yaml
      when: ansible_facts['os_family'] == "NixOS"

    - name: Apply generation on next boot
      ansible.builtin.command: "{{ nix_build_result }}/bin/switch-to-configuration boot"
      become: true
      when: ansible_facts['os_family'] == "NixOS"

