[picture-in-picture]
id = "hkgfoiooedgoejojocmhlaklaeopbecg"

[link-to-text-fragment]
id = "pbcodcjpfjdpcineamnnmbkkmkdpajjg"

[ga-optout]
id = "fllaojicojecljbmefodhfapmkghcbnh"

[iba-optout]
id = "gbiekjoijknlhijdjbaadobpkdhmoebb"

[gnome-shell-integration]
id = "gphhapmejobijbbhgpjhcjognlahblep"

[browserpass]
id = "naepdomgkenhinolocfifgehidddafch"
