keys:
  - &users:
    - &bjorn 87AA3657F508C4F29FE0C2587B0FF33FF90110C7

  # Creating proxies until getting an explanation for Mic92/sops-nix#287
  # on why sops.gnupg.home does not work
  - &proxies:
    - &bjorn_p age13cgztmk4ncsf0j4dquhae5j9memjnpux24ec3hn4rjxlj4ecrgaqxuxcku

  - &hosts:
    - &irazu age17gm2cha0zhf55fmchuzq0d2hvggp42xxq3hheqgmhy4cmge7s42qvvqn5f
    - &arenal age1qc7yq0j066kh8r4lftr4wkrfpqmqjkuxl97c6jqgdkjkggfvg9tqhku4h8
    - &barva age1evuvvyh966c5crnmx0cyevqw6dqnn76lyqvmmla633j0mvsufsysc5w9em

creation_rules:
  - path_regex: system/hosts/common/secrets.ya?ml$
    key_groups:
    - pgp:
      - *bjorn
      age:
      - *irazu
      - *arenal
      - *barva
  - path_regex: system/hosts/arenal/secrets.ya?ml$
    key_groups:
    - pgp:
      - *bjorn
      age:
      - *arenal
  - path_regex: system/hosts/irazu/secrets.ya?ml$
    key_groups:
    - pgp:
      - *bjorn
      age:
      - *irazu
  - path_regex: system/hosts/barva/secrets.ya?ml$
    key_groups:
    - pgp:
      - *bjorn
      age:
      - *barva
  - path_regex: home/users/bjorn/secrets.ya?ml$
    key_groups:
    - pgp:
      - *bjorn
      age:
      - *bjorn_p
