# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  Anime4K-rs = {
    pname = "Anime4K-rs";
    version = "a47a8ac21f81d6a3bcbdf6fc338b6546f1a51d29";
    src = fetchFromGitHub {
      owner = "andraantariksa";
      repo = "Anime4K-rs";
      rev = "a47a8ac21f81d6a3bcbdf6fc338b6546f1a51d29";
      fetchSubmodules = false;
      sha256 = "sha256-7CvYbc4U9kIwV2ELkd4lqKC1ynCwqizpXBXJamSGDig=";
    };
    date = "2020-08-09";
  };
  aichat = {
    pname = "aichat";
    version = "bb1c34d0b84e342232c4e0b7f3f0c1fb3a9334c0";
    src = fetchFromGitHub {
      owner = "sigoden";
      repo = "aichat";
      rev = "bb1c34d0b84e342232c4e0b7f3f0c1fb3a9334c0";
      fetchSubmodules = false;
      sha256 = "sha256-KZmZeYoOKZiEaMKNH2um3K+C8YmQ5RXEXg6EanBotZg=";
    };
    date = "2024-11-16";
  };
  av1an = {
    pname = "av1an";
    version = "f5497931d1d3c557938e77d9f42c740d02c0e740";
    src = fetchFromGitHub {
      owner = "master-of-zen";
      repo = "av1an";
      rev = "f5497931d1d3c557938e77d9f42c740d02c0e740";
      fetchSubmodules = false;
      sha256 = "sha256-1VmEz2YD1j7NCKkpDpX8RBkJ8EoOojrH1uiw2PynCRQ=";
    };
    date = "2024-11-07";
  };
  bypy = {
    pname = "bypy";
    version = "9e1530725f93d941d82596895d6fc36738f72f1c";
    src = fetchFromGitHub {
      owner = "houtianze";
      repo = "bypy";
      rev = "9e1530725f93d941d82596895d6fc36738f72f1c";
      fetchSubmodules = false;
      sha256 = "sha256-dZclceNcTVrjzm5VSvQz088q2M46zMImk8BA7/iIYUk=";
    };
    date = "2024-05-02";
  };
  candy = {
    pname = "candy";
    version = "cc76861c833692c93bd8b5e7b18a665ffce0a565";
    src = fetchFromGitHub {
      owner = "lanthora";
      repo = "candy";
      rev = "cc76861c833692c93bd8b5e7b18a665ffce0a565";
      fetchSubmodules = false;
      sha256 = "sha256-ytR9bINEBs8MWIMrDYJ7tuvLaB+5irrOwWGd8ukVvjc=";
    };
    date = "2024-11-05";
  };
  fww-checkin-rs = {
    pname = "fww-checkin-rs";
    version = "92ce21ff1556e709384c6e817157488db2a9eb7d";
    src = fetchFromGitHub {
      owner = "1235467";
      repo = "fww-checkin-rs";
      rev = "92ce21ff1556e709384c6e817157488db2a9eb7d";
      fetchSubmodules = false;
      sha256 = "sha256-aGYHwuMhot9RQ2PXJhQBzHljXBVcbuaO3r6/gWK/jIU=";
    };
    date = "2024-11-16";
  };
  hyprland = {
    pname = "hyprland";
    version = "af83c825138386d269d69b3ef755b844a2eacb22";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "Hyprland";
      rev = "af83c825138386d269d69b3ef755b844a2eacb22";
      fetchSubmodules = true;
      sha256 = "sha256-wwFbcWfVYGwemw/GeSdXrSXmNjjdTUw0N8DU8McyZU8=";
    };
    date = "2024-11-16";
  };
  hyprwayland-scanner = {
    pname = "hyprwayland-scanner";
    version = "500c81a9e1a76760371049a8d99e008ea77aa59e";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprwayland-scanner";
      rev = "500c81a9e1a76760371049a8d99e008ea77aa59e";
      fetchSubmodules = true;
      sha256 = "sha256-VKR0sf0PSNCB0wPHVKSAn41mCNVCnegWmgkrneKDhHM=";
    };
    date = "2024-09-21";
  };
  idntag = {
    pname = "idntag";
    version = "0d2fcb286bfa5b7e9ec02d6d9c1d55dd2cf5da5f";
    src = fetchFromGitHub {
      owner = "d99kris";
      repo = "idntag";
      rev = "0d2fcb286bfa5b7e9ec02d6d9c1d55dd2cf5da5f";
      fetchSubmodules = false;
      sha256 = "sha256-u/WgEvGrGGfXfx/4iXLxy8mGKFsrA/nsD8CGv3MdS80=";
    };
    date = "2023-01-15";
  };
  koboldcpp = {
    pname = "koboldcpp";
    version = "fedc3874bd54ad7fd43f55ae52595ffb0144afc4";
    src = fetchFromGitHub {
      owner = "LostRuins";
      repo = "koboldcpp";
      rev = "fedc3874bd54ad7fd43f55ae52595ffb0144afc4";
      fetchSubmodules = true;
      sha256 = "sha256-6RvodNWO/IVGlKxC/zt0itYDzymhk+hEBpbmQ1jHigU=";
    };
    date = "2024-11-15";
  };
  libdrm = {
    pname = "libdrm";
    version = "f314a43f146d2cc4a86329cf6797178aa6ae5cc4";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/mesa/drm";
      rev = "f314a43f146d2cc4a86329cf6797178aa6ae5cc4";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-fBWEHjUX2rQEuca9qLQKvp1QFqaezPYxyfCd6G1dgMk=";
    };
    date = "2024-10-29";
  };
  llamafile = {
    pname = "llamafile";
    version = "41abfa3ea8d973b7e8847fc39755f8178f7e04f0";
    src = fetchFromGitHub {
      owner = "Mozilla-Ocho";
      repo = "llamafile";
      rev = "41abfa3ea8d973b7e8847fc39755f8178f7e04f0";
      fetchSubmodules = false;
      sha256 = "sha256-I569JEl5orMyGqAik3/w7M+qah/1YY0j3mJzEwPRQxg=";
    };
    date = "2024-11-16";
  };
  mieru = {
    pname = "mieru";
    version = "f794940b2e25937f82b2798f58bfbeb22a4b728b";
    src = fetchFromGitHub {
      owner = "enfein";
      repo = "mieru";
      rev = "f794940b2e25937f82b2798f58bfbeb22a4b728b";
      fetchSubmodules = false;
      sha256 = "sha256-GBIgymdvEMKwfd+6KvN+GuB6nffCnqqRK2gGCoF7VCY=";
    };
    date = "2024-11-16";
  };
  nbfc-linux = {
    pname = "nbfc-linux";
    version = "2046e4cc03fdaf403767333055d88bebc117eb10";
    src = fetchFromGitHub {
      owner = "nbfc-linux";
      repo = "nbfc-linux";
      rev = "2046e4cc03fdaf403767333055d88bebc117eb10";
      fetchSubmodules = false;
      sha256 = "sha256-xcMQb20Qcn8jpcYi9A9GfgSkp8+Z6jel44UlD5ukaNA=";
    };
    date = "2024-10-08";
  };
  ncmdump_rs = {
    pname = "ncmdump_rs";
    version = "2e7f77779f55f914fb505d996b16e829028240e3";
    src = fetchFromGitHub {
      owner = "iqiziqi";
      repo = "ncmdump.rs";
      rev = "2e7f77779f55f914fb505d996b16e829028240e3";
      fetchSubmodules = false;
      sha256 = "sha256-ryxjZFTknWEGHESo0OcoBv/+rCx+rCifoSsqNUaF+FM=";
    };
    date = "2024-09-23";
  };
  onedrive-fuse = {
    pname = "onedrive-fuse";
    version = "26ceb411527a5ec59af96d5ba96ca4ed2bb149a8";
    src = fetchFromGitHub {
      owner = "oxalica";
      repo = "onedrive-fuse";
      rev = "26ceb411527a5ec59af96d5ba96ca4ed2bb149a8";
      fetchSubmodules = false;
      sha256 = "sha256-U5BzPfcV+OtzAcBYMADcK3epqWcuJeSYPQIyVl9VmPo=";
    };
    date = "2024-08-03";
  };
  open-snell = {
    pname = "open-snell";
    version = "8d2645b8394b20dba744a860655e3092fc8ae052";
    src = fetchFromGitHub {
      owner = "icpz";
      repo = "open-snell";
      rev = "8d2645b8394b20dba744a860655e3092fc8ae052";
      fetchSubmodules = false;
      sha256 = "sha256-/gILrDXOXDYQ3cTUMbjHAzITdtC2O+4XO0pp1ulRAM4=";
    };
    date = "2022-04-19";
  };
  pynat = {
    pname = "pynat";
    version = "22a8f2a467bfb95003d35b139dad9fd5a1ca4e9d";
    src = fetchFromGitHub {
      owner = "aarant";
      repo = "pynat";
      rev = "22a8f2a467bfb95003d35b139dad9fd5a1ca4e9d";
      fetchSubmodules = false;
      sha256 = "sha256-2ig0mvePKglxz3IpBdiWsTfNJ9koODn34gHVRqbdwPk=";
    };
    date = "2022-08-20";
  };
  pystun3 = {
    pname = "pystun3";
    version = "5fdc6fa446924b575250acf853a8f7eea0c8b8c9";
    src = fetchFromGitHub {
      owner = "talkiq";
      repo = "pystun3";
      rev = "5fdc6fa446924b575250acf853a8f7eea0c8b8c9";
      fetchSubmodules = false;
      sha256 = "sha256-1QnfEHzkvjWURsApvTi4aVVz3MBNieQmVofmqUmgb4k=";
    };
    date = "2024-06-28";
  };
  qcm = {
    pname = "qcm";
    version = "f32c826a97514b2279a4335aaa4a6b3182c656bc";
    src = fetchFromGitHub {
      owner = "hypengw";
      repo = "Qcm";
      rev = "f32c826a97514b2279a4335aaa4a6b3182c656bc";
      fetchSubmodules = true;
      sha256 = "sha256-DmaqoORHoTtsFg2quX9q/neaRZjVugX49ykauU4Q1Ag=";
    };
    date = "2024-11-16";
  };
  reflac = {
    pname = "reflac";
    version = "a2dcaa2f5d3d23cf121934d5ff0e4d169a8f7a64";
    src = fetchFromGitHub {
      owner = "chungy";
      repo = "reflac";
      rev = "a2dcaa2f5d3d23cf121934d5ff0e4d169a8f7a64";
      fetchSubmodules = false;
      sha256 = "sha256-vrHDzDTrLPaDHXwgWJplCOQT6YdcWaEu28Rx1yXlgNk=";
    };
    date = "2021-08-16";
  };
  rescrobbled = {
    pname = "rescrobbled";
    version = "9c540d288f7dd1b0fd2a7058776db27d591db15a";
    src = fetchFromGitHub {
      owner = "InputUsername";
      repo = "rescrobbled";
      rev = "9c540d288f7dd1b0fd2a7058776db27d591db15a";
      fetchSubmodules = false;
      sha256 = "sha256-o5k5xk5z19oVOGE1p+t5MGQP7/YRZhqp3p786G3H7GA=";
    };
    date = "2024-08-20";
  };
  sakaya = {
    pname = "sakaya";
    version = "31b96a453f91e85a48423b5bd6548e498710951e";
    src = fetchFromGitHub {
      owner = "donovanglover";
      repo = "sakaya";
      rev = "31b96a453f91e85a48423b5bd6548e498710951e";
      fetchSubmodules = false;
      sha256 = "sha256-Fpi3eQDCdjS89cUKdnVr+jYehD8TgIslBbYooEesGK0=";
    };
    date = "2024-11-07";
  };
  suyu = {
    pname = "suyu";
    version = "ee365bad9501c73ff49936e72ec91cd9c3ce5c24";
    src = fetchgit {
      url = "https://git.suyu.dev/suyu/suyu";
      rev = "ee365bad9501c73ff49936e72ec91cd9c3ce5c24";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-vw9VcSbCaG4MS0PL/fJ73CDALLbd3n0CBT7gkyp5hRc=";
    };
    date = "2024-10-06";
  };
  sway = {
    pname = "sway";
    version = "96db66abf0622c8590d60ad6638b35d90e185f60";
    src = fetchFromGitHub {
      owner = "swaywm";
      repo = "sway";
      rev = "96db66abf0622c8590d60ad6638b35d90e185f60";
      fetchSubmodules = true;
      sha256 = "sha256-WBsGwUFb9/JVi0eAi8exYR/w/Bs6ZWGabscWJA0QD9Y=";
    };
    date = "2024-11-16";
  };
  swgp-go = {
    pname = "swgp-go";
    version = "800260adb8f338c6d605680fd144147463c0767b";
    src = fetchFromGitHub {
      owner = "database64128";
      repo = "swgp-go";
      rev = "800260adb8f338c6d605680fd144147463c0767b";
      fetchSubmodules = false;
      sha256 = "sha256-ufvq4i7RPKtGJLPodHTEdW5IJZWaL3+pnbQfNI+YPVA=";
    };
    date = "2024-11-09";
  };
  wayland = {
    pname = "wayland";
    version = "f67db75ec118f6ec64e60113dbdecb20b4ea1abd";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wayland/wayland";
      rev = "f67db75ec118f6ec64e60113dbdecb20b4ea1abd";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-59+WuNJB1qjSslyxI6nj9tut/ULS5uCiOJ/s74H5pAU=";
    };
    date = "2024-10-18";
  };
  wayland-protocols = {
    pname = "wayland-protocols";
    version = "fe3d5448be6cdefc49746c97c9361c1750ae89f6";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wayland/wayland-protocols";
      rev = "fe3d5448be6cdefc49746c97c9361c1750ae89f6";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-YcmueNNzBsWAnMs378f57F7KA1F/GtvB1v/cF4NBisQ=";
    };
    date = "2024-11-07";
  };
  waylyrics = {
    pname = "waylyrics";
    version = "4eabc0d281b281d0ea8f214863a67fb9313fb440";
    src = fetchFromGitHub {
      owner = "waylyrics";
      repo = "waylyrics";
      rev = "4eabc0d281b281d0ea8f214863a67fb9313fb440";
      fetchSubmodules = false;
      sha256 = "sha256-tDBavtjy6jfWt0JsaSntf3oPHYMbxdGI5ZxK2cjKdac=";
    };
    date = "2024-11-16";
  };
  wlroots = {
    pname = "wlroots";
    version = "0b720ae5ea161619d8092ae8d44fd7e65117818e";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wlroots/wlroots";
      rev = "0b720ae5ea161619d8092ae8d44fd7e65117818e";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-/fKlUsKIQsXvIb/J+2eJLwh4HEWfguikEwnALH3OMf4=";
    };
    date = "2024-11-12";
  };
}
