---
name: Updaters
'on':
  schedule:
    - cron: '13 1 * * *'  # 01:13 UTC every day
  workflow_dispatch:

jobs:
  updater:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    strategy:
      matrix:
        package:
          - llr
          - mkvcleaner
          - goprocmgr
          # - g90updatefw

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: etu
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: 'Update ${{ matrix.package }}'
        run: 'nix shell nixpkgs#nix-update -c nix-update ${{ matrix.package }}'

      - name: 'Build ${{ matrix.package }}'
        run: 'nix build .#${{ matrix.package }}'

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "cron(${{ matrix.package }}): Update ${{ matrix.package }} package"
