---
name: Updaters
'on':
  schedule:
    - cron: '13 1 * * *'

jobs:
  updater:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        package:
          - llr
          - mkvcleaner
          - g90updatefw

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: etu
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: 'Update ${{ matrix.package }}'
        run: 'nix shell nixpkgs#nix-update -c nix-update ${{ matrix.package }}'

      - name: 'Build ${{ matrix.package }}'
        run: 'nix build .#${{ matrix.package }}'

      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "cron(${{ matrix.package }}): Update ${{ matrix.package }} package"
