stages:
  - check
  - build
  - deploy

.common:
  image: nixos/nix
  variables:
    NIX_PATH: "nixpkgs=channel:nixpkgs-unstable"
  before_script:
    - |
      cat >> /etc/nix/nix.conf << EOF
      experimental-features = nix-command flakes
      EOF
    - |
      if [[ -n "$NIXREMOTE_SSH" && -n "$NIXREMOTE_HOST_KEY" ]]; then
        mkdir -p /etc/ssh
        cp "$NIXREMOTE_SSH" /etc/nix/id_nixremote
        echo "" >> /etc/nix/id_nixremote # add trailing newline because GitLab doesn't and it's required
        chmod 400 /etc/nix/id_nixremote
        cat <"$NIXREMOTE_HOST_KEY" >> /etc/ssh/ssh_known_hosts
        cat >> /etc/nix/nix.conf << EOF
      builders = ssh://nixremote@aarch64-linux-1.build.999eagle.moe aarch64-linux /etc/nix/id_nixremote 8 1 nixos-test,kvm,big-parallel
      EOF
        export AARCH64=true
      fi
    - nix-channel --update
    - nix-env --install --attr nixpkgs.cachix --attr nixpkgs.nix-build-uncached
    - test -n "$CACHIX_CACHE_NAME" && cachix use "$CACHIX_CACHE_NAME"
    - nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

check:
  stage: check
  extends: .common
  script:
    - nix flake check
    - |
      nix-env -f . -qa \* --meta \
        --allowed-uris https://static.rust-lang.org \
        --option restrict-eval true \
        --option allow-import-from-derivation true \
        --drv-path --show-trace \
        -I nixpkgs=$(nix-instantiate --find-file nixpkgs) \
        -I ./

build:
  stage: build
  extends: .common
  variables:
    CACHIX_CACHE_NAME: "999eagle-nur-packages"
  script:
    - |
      if [ -z "$CACHIX_AUTH_TOKEN" ]; then
        echo "no cachix auth token set!"
        command=""
      else
        command="cachix watch-exec $CACHIX_CACHE_NAME --"
      fi
    - ${command} nix-build-uncached ci.nix -A cacheOutputs
    - test -z "$AARCH64" || ${command} nix-build-uncached ci.nix --arg pkgs 'import <nixpkgs> {system="aarch64-linux";}' -A cacheOutputs

deploy:
  stage: deploy
  image: curlimages/curl
  script:
    - curl -XPOST https://nur-update.nix-community.org/update?repo=999eagle
