---
name: "Update sources"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-sources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Print nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'

      - name: Update Firefox sources
        working-directory: ./pkgs/firefox-darwin
        run: nix-shell -p 'with import <nixpkgs> {}; callPackage ./update.nix {}' --run "firefox-update-source"

      - name: Update Librewolf sources
        working-directory: ./pkgs/librewolf-darwin
        run: nix-shell -p 'with import <nixpkgs> {}; callPackage ./update.nix {}' --run "librewolf-update-source"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: "Update sources"
          add: 'sources.json'
