name: Automatically update
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */96 * * *'

jobs:
  nvfetcher:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.0
      with:
          fetch-depth: 0
    - name: Cache nvfetcher
      uses: actions/cache@v4.1.0
      with:
        path: ~/.local/share/nvfetcher
        key: ${{ runner.os }}-nvfetcher
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: hakutaku-cache
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Run nvfetcher
      run: |
        nix shell .#buildtools --command nurpkgs-nvfetcher

    #- name: Run flake check
    #  run: nix flake check

    - name: Commit changes
      #if: ${{ env.COMMIT_MSG != null }}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: update pkgs"
