name: Automatically update
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */2 * * *'

jobs:
  nvfetcher:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
          fetch-depth: 0
    - name: Cache nvfetcher
      uses: actions/cache@v3.2.6
      with:
        path: ~/.local/share/nvfetcher
        key: ${{ runner.os }}-nvfetcher
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Run nvfetcher
      run: |
        nix develop .#buildtools --command nurpkgs-nvfetcher

    - name: Run flake check
      run: nix flake check

    - name: Commit changes
      if: ${{ env.COMMIT_MSG != null }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ env.COMMIT_MSG }}
