# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "1x9fx7xpa0z3lwf9swidybqypaymppqlkf9l4bq9n7m42vnwk762";
    aarch64-linux = "01pyvj2vghldfcm9zjpp3k5d05i64jq8gjaybq0i0mqmn9wlyplh";
    x86_64-darwin = "0kgsiln4qx855aw37xwxks9bmw67r8h7w1yxapv1pl3bhg5aywhd";
    aarch64-darwin = "1lwq1ga3rs267894ybnanmmmk114cfj1m4qsgvc2cmxlzih5j312";
  };

  urlMap = {
    x86_64-linux = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.2.0/javascript-package-delegator_1.2.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.2.0/javascript-package-delegator_1.2.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.2.0/javascript-package-delegator_1.2.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.2.0/javascript-package-delegator_1.2.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "javascript-package-delegator";
  version = "1.2.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./jpd $out/bin/jpd
  '';

  system = system;

  meta = {
    description = "A CLI for executing JavaScript package manager commands based on lock files. Supports npm, yarn, pnpm, bun, and deno.";
    homepage = "https://github.com/louiss0/javascript-package-delegator";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
