# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "1vdi1ki2m0d0b5p8pm68xjy1kb0as3cdaa5di42ip7lh0aia08fs";
    aarch64-linux = "0qdalpf7b3vp6049gyxqwi4m49p4fj1m5k4jsx8ymnq5yxvbv7d1";
    x86_64-darwin = "1r65y6di28w7a4x25fc2illr3c67q9frh3hyisr9y8i72fnllzry";
    aarch64-darwin = "1bvh18f1l7lqrcbms96kq41srl26k3lknzbma2m45mv5vi27d4vj";
  };

  urlMap = {
    x86_64-linux = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.1.0/javascript-package-delegator_1.1.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.1.0/javascript-package-delegator_1.1.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.1.0/javascript-package-delegator_1.1.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.1.0/javascript-package-delegator_1.1.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "javascript-package-delegator";
  version = "1.1.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./jpd $out/bin/jpd
  '';

  system = system;

  meta = {
    description = "A CLI for executing Javascript Package Manager Commands based on lock files. Supported's deno,bun, and all node package managers";
    homepage = "https://github.com/louiss0/javascript-package-delegator";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
