name: "Update"
on:
  workflow_dispatch:
  schedule:
    #- cron:  '0 * * * *' # every hour
    #- cron:  '0 */6 * * *' # every 6 hours
    #- cron:  '0 */12 * * *' # every 12 hours
    - cron:  '0 0 * * *' # every day
  push:
    branches:
      - master
jobs:
  update_nur:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # TODO what does "depth 0" mean? deep clone?
        #fetch-depth: '0'
        fetch-depth: '1'
    - uses: cachix/install-nix-action@v25
      with:
        #nix_path: nixpkgs=channel:nixos-unstable
        nix_path: nixpkgs=channel:nixpkgs-unstable
        #extra_nix_config: |
        #  experimental-features = nix-command flakes
        enable_kvm: false
    #- uses: DeterminateSystems/nix-installer-action@main
    #- uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies
    # setuptools provides distutils
    - run: pip install requests aiohttp setuptools
    - name: update nur
      run: date ; ./ci/update-nur.sh
      env:
        # https://github.com/your_name/NUR/settings/secrets/actions
        API_TOKEN_GITHUB: '${{ secrets.API_TOKEN_GITHUB }}'
        API_USER_GITHUB: '${{ secrets.API_USER_GITHUB }}'
        GRAPHQL_TOKEN_GITHUB: '${{ secrets.GRAPHQL_TOKEN_GITHUB }}'
        FORCE_NUR_SEARCH_UPDATE: '${{ vars.FORCE_NUR_SEARCH_UPDATE }}'
