name: "Test"
on:
  workflow_dispatch:
  schedule:
    # chosen by fair dice rolling
    - cron:  '05 4 * * *'
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      fetch-depth: '0'
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: update nur / nur-combined
      run: ./ci/update-nur.sh
      env:
        API_TOKEN_GITHUB: '${{ secrets.API_TOKEN_GITHUB }}'
    - name: update nur-search/data/packages.json
      run: ./ci/update-nur-search.sh
      env:
        API_TOKEN_GITHUB: '${{ secrets.API_TOKEN_GITHUB }}'
